// <auto-generated />
using DaftechCrm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DaftechCrm.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813000000_AddAccountRefId")]
    partial class AddAccountRefId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            CurrentModel.Build(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
